name: Docker Image CI

on:
  pull_request:
    branches:
      - oli-kis

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log into Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: olikis
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push to docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: olikis/planio:latest

      # Open deploy url from render to trigger deploy
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_CURL_URL }}
